-- HxH5e SystemDB (Shared) -- Nucleo (Parte 1/2)
-- Portado de js/data/config.js (SYSTEM_DB) do repo Criadores-HxH-5e/Ficha_HxH5e
-- via extracao automatizada (Node -> JSON -> Lua). Gerado em 2026-08-27.
-- Contem: classes (categorias de Nen), xpTable, skills, otherSkills,
-- pointBuyCosts, skillMap. Racas/antecedentes vem em SystemDB_Racas e
-- SystemDB_Antecedentes (proxima leva) por serem grandes demais para 1 modulo so.

return {
	classes = {
		{
			id = "INTENSIFICAÇÃO",
			color = "#00ff9d",
			label = "INTENSIFICAÇÃO",
			angle = 270,
			desc = "Aura expressa maior poder, cura e resistência",
		},
		{
			id = "TRANSMUTAÇÃO",
			color = "#d946ef",
			label = "TRANSMUTAÇÃO",
			angle = 330,
			desc = "Aura assume outra(s) propriedades(s)",
		},
		{
			id = "MATERIALIZAÇÃO",
			color = "#ff0055",
			label = "MATERIALIZAÇÃO",
			angle = 30,
			desc = "Aura cria e altera matéria física",
		},
		{
			id = "ESPECIALIZAÇÃO",
			color = "#00f0ff",
			label = "ESPECIALIZAÇÃO",
			angle = 90,
			desc = "Aura se apresenta de maneira inovadora",
		},
		{
			id = "MANIPULAÇÃO",
			color = "#9ca3af",
			label = "MANIPULAÇÃO",
			angle = 150,
			desc = "Aura manipula objetos, matéria ou seres vivos",
		},
		{
			id = "EMISSÃO",
			color = "#ffe600",
			label = "EMISSÃO",
			angle = 210,
			desc = "Aura se mantém forte fora do corpo e em longas distâncias",
		},
	},
	xpTable = {
		50,
		150,
		350,
		500,
		800,
		1000,
		1500,
		2500,
		3200,
		4000,
		5000,
		6500,
	},
	skills = {
		"TR de FOR",
		"TR de DES",
		"TR de CON",
		"TR de INT",
		"TR de SAB",
		"TR de PRE",
		"Acrobacia",
		"Arcanismo",
		"Atletismo",
		"Atuação",
		"Enganação",
		"Furtividade",
		"História",
		"Intimidação",
		"Intuição",
		"Investigação",
		"Lidar com Animais",
		"Medicina",
		"Natureza",
		"Percepção",
		"Persuasão",
		"Prestidigitação",
		"Religião",
		"Sobrevivência",
	},
	otherSkills = {
		"Armas Marciais corpo-a-corpo",
		"Armas Marciais à distância",
		"Armas Simples corpo-a-corpo",
		"Armas Simples à distância",
		"Equipamentos de Proteção e Armaduras Médias",
		"Equipamentos de Proteção e Armaduras Pesadas",
		"Equipamentos Improvisados/Manufaturados (Bugigangas e Armas de Hatsus criativos)",
		"Científicas/Explosivas",
		"Linguas Antigas e Culturas",
		"Armas de Cerco",
		"Kits",
	},
	pointBuyCosts = {
		[1] = -20,
		[2] = -17,
		[3] = -14,
		[4] = -11,
		[5] = -8,
		[6] = -6,
		[7] = -4,
		[8] = -2,
		[9] = -1,
		[10] = 0,
		[11] = 1,
		[12] = 2,
		[13] = 3,
		[14] = 4,
		[15] = 6,
		[16] = 8,
		[17] = 11,
		[18] = 14,
		[19] = 17,
		[20] = 20,
		[21] = 23,
		[22] = 26,
		[23] = 29,
		[24] = 32,
		[25] = 35,
		[26] = 38,
		[27] = 41,
		[28] = 44,
		[29] = 47,
		[30] = 50,
	},
	skillMap = {
		FOR = {
			"Atletismo",
		},
		DES = {
			"Acrobacia",
			"Furtividade",
			"Prestidigitação",
		},
		CON = {},
		INT = {
			"Arcanismo",
			"História",
			"Investigação",
			"Natureza",
			"Religião",
		},
		SAB = {
			"Lidar com Animais",
			"Intuição",
			"Medicina",
			"Percepção",
			"Sobrevivência",
		},
		PRE = {
			"Atuação",
			"Enganação",
			"Intimidação",
			"Persuasão",
		},
	},
}
